#!/bin/bash

#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
#END COLORS

nmapipscan(){
echo '[+] Please enter your target IP address ---> '
read targip
echo '[+] What ports would you like to scan on --->'
echo '[*] Starting Port ---> '
read startport
echo '[*] End Port ---> '
read endport
#nmap -T4 -p$startport-$endport $targip
gnome-terminal --command="bash -c 'nmap -T4 -A -sC -vv -p$startport-$endport $targip; $SHELL'"
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

sleep 1
}
nmapudpscan(){
echo '[+] Please enter your target IP address ---> '
read targip
echo '[+] What ports would you like to scan on --->'
echo '[*] Starting Port ---> '
read startport
echo '[*] End Port ---> '
read endport
#nmap -T4 -p$startport-$endport $targip
gnome-terminal --command="bash -c 'nmap -T4 -sU -vv -p$startport-$endport $targip; $SHELL'"
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

}

niktowebscan(){
printf  "${YLLW}[+] Enter the URL you would like to scan ---> "
read url
#nikto -h $url
gnome-terminal --command="bash -c 'nikto -h $url; $SHELL'"
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

sleep 1
}

netscan(){
echo 'Enter your subnet ---> '
read subnet
echo 'Example | 192.168.0.0/24'
#nmap -sn $subnet
gnome-terminal --command="bash -c 'nmap -sn $subnet; $SHELL'"
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

sleep 1
}

sniffer(){
echo '[+] Enter target BSSID ---> '
read bssid
echo '[+] Enter the channel # ---> '
read channel
echo '[+] Choose a name to save your .cap file ---> '
read filename
#airodump-ng --bssid $bssid --channel $channel --write $filename wlan0mon
gnome-terminal --command="bash -c 'airodump-ng --bssid $bssid --channel $channel --write $filename wlan0mon; $SHELL'"
#fixed
clear
printf "${GREEN}
------------------------------------
[✓] 	FINISHED SNIFFING	[✓] |
------------------------------------"

sleep 1
#working
}

wifiscan(){
#airmon-ng check kill
#airmon-ng start wlan0
echo '[*] Wlan0 is now in Monitor Mode -----> wlan0mon'
sleep 1
gnome-terminal --command="bash -c 'airmon-ng check kill; airmon-ng start wlan0 ;airodump-ng --band abg wlan0mon; $SHELL'" #airodump-ng --band abg wlan0mon
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

sleep 1
}

managedmode(){
echo [+] Wlan0 will now be returned to managed mode!
#airmon-ng stop wlan0mon
#service NetworkManager restart
gnome-terminal --command="bash -c 'airmon-ng stop wlan0mon; service NetworkManager restart;$SHELL'"
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] WIFI CARD ----> MANAGED MODE [✓] |
-------------------------------------"

sleep 1
}

usrmsg(){
echo ''
echo ''
echo "Thanks for downloading and running my script. It took me a little bit of time to learn bash scripting to put this together. But i wanted to share it with the community! I know it's simple but i hope it helps save some time. I plan to take suggestions on other functions i can implement and release, leave a comment or send me a message with your ideas!
	
	*P.S. | Feel free to simply edit the source code to customize your own unique patch.*
	 
							Enjoy!"
echo ''
echo ''
}
update(){
updater
clear
clear
reset
./autohack
exit
}



updater(){
clear
printf "${GREEN}
------------------------------------
[+]      Patch 3.83             [+] |
------------------------------------"
printf "${GREEN}
------------------------------------
[✓]      ... UPDATING ...	[✓] |
------------------------------------"
echo ''
echo ''
git add autohack
git stash save
git pull 

sleep 1


printf "${GREEN}
------------------------------------
[✓] 		UPDATED		[✓] |
------------------------------------"
printf "${GREEN}
------------------------------------
[✓] 	You are now up-to-date	[✓] |
------------------------------------"
printf "${GREEN}
------------------------------------
[✓] 	     Hack on.		[✓] |
------------------------------------"
printf "${YLLW}
------------------------------------
[!] ...Restarting Autohack...   [!] |
------------------------------------"

#gnome-terminal -- ./autohack
sleep 5


}

arpscan(){
gnome-terminal --command="bash -c 'arp-scan -l;$SHELL'" 2&>1 >/dev/null
clear

}

credits(){
clear
echo ''
echo ''
echo ''
echo ''
echo ''	
printf "${YLLW}
________________________________
Created by:                     |           	
--------------------------------|            	
${RED}	dxrk${YLLW}      		|             	
				|            	
--------------------------------|           	
Contributors:                   |          	
--------------------------------|          	
${GREEN}	asorg ${YLLW}   	        |         	
				|              	
--------------------------------                   "
sleep 2
echo ''
echo ''
echo ''
}
kaliupgrade_update(){
clear
sudo apt-get update
sudo apt-get upgrade
sleep 3
clear
clear
reset
./attempt
exit
}
searchsploit(){
printf 'Searchsploit ---> '
read query
gnome-terminal --command="bash -c 'searchsploit $query;$SHELL'"
printf "${GREEN}
-------------------------------------
[✓] FINISHED SEARCHING		 [✓] |
-------------------------------------"
}
smbclient(){
printf 'Enter username ---> '
read usrname
printf 'Enter target IP Address ---> '
read targip
gnome-terminal --command="bash -c 'smbclient -U '$usrname' -L //$targip;$SHELL'"
printf "${GREEN}
-------------------------------------
[✓] 	     💀FINISHED💀	 [✓] |
-------------------------------------"
}
gobuster(){
printf "Target IP ---> "
read targip
printf "Path to wordlist ---> "
read wordlist
gnome-terminal --command="bash -c 'gobuster dir -v -w $wordlist -u $targip;$SHELL'"
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"
}
deauth(){
printf "Enter target BSSID ---> "
read bssid
printf "Enter channel of AP ---> "
read channel
printf "Name of your wireless interface ---> "
read wlan
gnome-terminal --command="bash -c 'airodump-ng $wlan --bssid $bssid --channel $channel ;$SHELL'"
gnome-terminal --command="bash -c 'aireplay-ng -0 0 -a $bssid $wlan;$SHELL'"
}
exploitation(){
printf "${RED}
    █████╗ ██╗   ██╗████████╗ ██████╗   ██╗  ██╗ █████╗  ██████╗██╗  ██╗    
   ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗  ██║  ██║██╔══██╗██╔════╝██║ ██╔╝   
   ███████║██║   ██║   ██║   ██║   ██║  ███████║███████║██║     █████╔╝    
   ██╔══██║██║   ██║   ██║   ██║   ██║  ██╔══██║██╔══██║██║     ██╔═██╗    
   ██║  ██║╚██████╔╝   ██║   ╚██████╔╝  ██║  ██║██║  ██║╚██████╗██║  ██╗  
   ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
                                    v3.83  
${NC}"
#OPTIONS START
printf "${YLLW}
-------------------------------------------------------------------------------
                               💀 Exploitation 💀                              |                                                
-------------------------------------------------------------------------------
1)  Use SMBClient (smbclient)            |                                     |
                    			 |                    	               |
	         			 |				       |
	 				 |                                     |
   					 |                                     |
                                         |                                     |                
           MORE SOON!                    |            MORE SOON!               |                
                                         |                                     |                
-------------------------------------------------------------------------------
Type 'back' to go return to the main menu
Type 'exit' to quit the program 
${DG}
Hacking made simple.

 ̿̿ ̿̿ ̿'̿'\̵͇\з= ( ▀ ͜͞ʖ▀) =ε/̵͇/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
 
${NC}"
#OPTIONS END
printf "${LR}AutoHack${NC}${YLLW} |${NC}${DG} root💀kali ${YLLW}--> "
read choice

if [ $choice == 1 ]
then
        smbclient

elif [ $choice == 'back' ]
then
	continue
	clear

elif [ $choice == 'exit' ]
then
	exit


else
	clear
	echo You did not select a valid option.
	exploitation

fi
}
scan_enum(){
printf "${RED}
    █████╗ ██╗   ██╗████████╗ ██████╗   ██╗  ██╗ █████╗  ██████╗██╗  ██╗    
   ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗  ██║  ██║██╔══██╗██╔════╝██║ ██╔╝   
   ███████║██║   ██║   ██║   ██║   ██║  ███████║███████║██║     █████╔╝    
   ██╔══██║██║   ██║   ██║   ██║   ██║  ██╔══██║██╔══██║██║     ██╔═██╗    
   ██║  ██║╚██████╔╝   ██║   ╚██████╔╝  ██║  ██║██║  ██║╚██████╗██║  ██╗  
   ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
                                     
${NC}"
#OPTIONS START
printf "${YLLW}
-------------------------------------------------------------------------------
                                Scanning/Enumeration                           |                                                
-------------------------------------------------------------------------------
1)  Nikto Web Scan (Nikto)               |                                     |
2)  NMAP Scan (NMAP)                     |                                     |
2a) NMAP UDP Scan (NMAP)	         |				       |
3)  Gobuster Dir Scan (Gobuster)	 |                                     |
4)  Searchsploit a vuln (searchsploit)   |                                     |
                                         |                                     |                
           MORE SOON!                    |            MORE SOON!               |                
                                         |                                     |                
-------------------------------------------------------------------------------
Type 'back' to go return to the main menu
Type 'exit' to quit the program 
${DG}
Hacking made simple.

 ̿̿ ̿̿ ̿'̿'\̵͇\з= ( ▀ ͜͞ʖ▀) =ε/̵͇/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
 
${NC}"
#OPTIONS END
printf "${LR}AutoHack${NC}${YLLW} |${NC}${DG} root💀kali ${YLLW}--> "
read choice

if [ $choice == 1 ]
then
        niktowebscan

elif [ $choice == 2 ]
then
        nmapipscan

elif [ $choice == '2a' ]
then
        nmapudpscan
elif [ $choice == 3 ]
then
	gobuster
elif [ $choice == 4 ]
then
	searchsploit

elif [ $choice == 'back' ]
then
	continue
	clear

elif [ $choice == 'exit' ]
then
	exit


else
	clear
	echo You did not select a valid option.
	scan_enum

fi
}


wifi_exploit(){
printf "${RED}
    █████╗ ██╗   ██╗████████╗ ██████╗   ██╗  ██╗ █████╗  ██████╗██╗  ██╗    
   ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗  ██║  ██║██╔══██╗██╔════╝██║ ██╔╝   
   ███████║██║   ██║   ██║   ██║   ██║  ███████║███████║██║     █████╔╝    
   ██╔══██║██║   ██║   ██║   ██║   ██║  ██╔══██║██╔══██║██║     ██╔═██╗    
   ██║  ██║╚██████╔╝   ██║   ╚██████╔╝  ██║  ██║██║  ██║╚██████╗██║  ██╗  
   ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
                                      
${NC}"
#OPTIONS START
printf "${YLLW}
-------------------------------------------------------------------------------
                                        WiFi                                   |                
-------------------------------------------------------------------------------
1)  Scan for Hosts (Aircrack)            |                                     |
1a) Scan for Hosts #2 (Arp)              |				       |
2)  Scan for WiFi		         |                                     |
3)  Packet Sniffer (Aircrack)  		 |				       |
4)  Perform Deauth Attack (Aireplay)     |         MORE SOON!                  |                                        
5)  WiFi Card --> Managed Mode           |                                     |
                                         |                                     |
                                         |                                     |
-------------------------------------------------------------------------------
Type 'back' to return to the main menu
Type 'exit' to quit the program 
${DG}
Hacking made simple.

 ̿̿ ̿̿ ̿'̿'\̵͇\з= ( ▀ ͜͞ʖ▀) =ε/̵͇/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
 
${NC}"
#OPTIONS END
printf "${LR}AutoHack${NC}${YLLW} |${NC}${DG} root💀kali ${YLLW}--> "
read choice
if [ $choice == 1 ]
then
        netscan

elif [ $choice == '1a' ]
then
        arpscan

elif [ $choice == 2 ]
then
        wifiscan


elif [ $choice == 3 ]
then
        sniffer
        
elif [ $choice == 4 ]
then
        deauth
        
        
elif [ $choice == 5 ]
then
        managedmode


elif [ $choice == 'back' ]
then
	continue
	clear

elif [ $choice == 'exit' ]
then
	exit

else
	clear
	echo You did not select a valid option.
	wifi_exploit
fi
}

options(){
printf "${RED}
    █████╗ ██╗   ██╗████████╗ ██████╗   ██╗  ██╗ █████╗  ██████╗██╗  ██╗    
   ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗  ██║  ██║██╔══██╗██╔════╝██║ ██╔╝   
   ███████║██║   ██║   ██║   ██║   ██║  ███████║███████║██║     █████╔╝    
   ██╔══██║██║   ██║   ██║   ██║   ██║  ██╔══██║██╔══██║██║     ██╔═██╗    
   ██║  ██║╚██████╔╝   ██║   ╚██████╔╝  ██║  ██║██║  ██║╚██████╗██║  ██╗  
   ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝   ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
                                      
${NC}"
#OPTIONS START
printf "${YLLW}
-------------------------------------------------------------------------------
                                       Other                                   |                
-------------------------------------------------------------------------------
1) Check for Updates                                                           |
2) Update & Upgrade your Kali OS                                               |
3) Message to users                                                            |                                        
4) Credits                                                                     |
                                                                               |
                                                                               |
-------------------------------------------------------------------------------
Type 'back' to return to the main menu
Type 'exit' to quit the program 
${DG}
Hacking made simple.

 ̿̿ ̿̿ ̿'̿'\̵͇\з= ( ▀ ͜͞ʖ▀) =ε/̵͇/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
 
${NC}"
#OPTIONS END
printf "${LR}AutoHack${NC}${YLLW} |${NC}${DG} root💀kali ${YLLW}--> "
read choice
if [ $choice == 1 ]
then
        update

elif [ $choice == 2 ]
then
        kaliupgrade_update
elif [ $choice == 3 ]
then
        usrmsg

elif [ $choice == 4 ]
then
        credits

elif [ $choice == 'back' ]
then
	continue
	clear

elif [ $choice == 'exit' ]
then
        exit

else
	clear
        echo You did not select a valid option.
        options
fi

}




cli(){
printf "${RED}
    █████╗ ██╗   ██╗████████╗ ██████╗ 	██╗  ██╗ █████╗  ██████╗██╗  ██╗    
   ██╔══██╗██║   ██║╚══██╔══╝██╔═══██╗	██║  ██║██╔══██╗██╔════╝██║ ██╔╝   
   ███████║██║   ██║   ██║   ██║   ██║	███████║███████║██║     █████╔╝    
   ██╔══██║██║   ██║   ██║   ██║   ██║	██╔══██║██╔══██║██║     ██╔═██╗    
   ██║  ██║╚██████╔╝   ██║   ╚██████╔╝	██║  ██║██║  ██║╚██████╗██║  ██╗  
   ╚═╝  ╚═╝ ╚═════╝    ╚═╝    ╚═════╝ 	╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝ 
   				      
${NC}"
#OPTIONS START
printf "${YLLW}
-------------------------------------------------------------------------------
                                       Menu 	                               |						
-------------------------------------------------------------------------------
1)  Scanning & Enumeration tools                                               |                                     
2)  WiFi tools								       |
3)  Exploitation                                                               |                                     
4)  Other                                                                      |
                                                                               |
                                                                               |                                 
-------------------------------------------------------------------------------
Type 'exit' to quit the program 
${DG}
Hacking made simple.

 ̿̿ ̿̿ ̿'̿'\̵͇̿̿\з= ( ▀ ͜͞ʖ▀) =ε/̵͇̿̿/’̿’̿ ̿ ̿̿ ̿̿ ̿̿
 
${NC}"
#OPTIONS END
printf "${LR}AutoHack${NC}${YLLW} |${NC}${DG} root💀kali ${YLLW}--> "
read choice
if [ $choice == 1 ]  
then
	clear
	scan_enum

elif [ $choice == 2 ] 
then
	clear
	wifi_exploit

elif [ $choice == 3 ] 
then
	clear
	exploitation
elif [ $choice == 4 ] 
then
	clear
	options

elif [ $choice == 'exit' ]
then
	exit

else
	clear
	echo You did not select a valid option.
	cli
fi
cli
}

cli



exit

 
