#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' #No color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=5.01
#END COLORS

apt-get update -y

apt-get upgrade -y
whereah=`which autohack`
cd ${whereah::-8} #in ah folder now
cd scripts/other/dependencies
./ScillaInstall
printf "\n ${GREEN}[✓] Scilla Installed [✓]${NC}"
sleep 2
./autoReconInstall
printf "\n ${GREEN}[✓] AutoRecon Installed [✓]${NC}"
sleep 2
apt install mdk3
printf "\n ${GREEN}[✓] mdk3 Installed [✓]${NC}"
sleep 2
./SETinstall
printf "\n ${GREEN}[✓] SET Installed [✓]${NC}"

