#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' #No color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
#END COLORS
apt install gccgo-go 
apt install golang-go
go get
go version
make linux



