#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' #No color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=5.01
#END COLORS
curpath=`pwd`
cdScilla=`cd ../../scanning_enumeration/scilla`
echo $cdScilla
go get
make linux
cd curpath
printf "${GREEN}[✓] SCILLA INSTALLED [✓]"

