#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' #No color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=5.01
#END COLORS
curpath=`pwd`
cdScilla=`cd ../../scanning_enumeration/scilla`
cd $cdScilla
sleep 1
printf "Now in scilla territory [✓] "
go get
sleep 1 
printf "Installing Go..."
go version
printf "Go installed [✓] "
make linux
printf "Installed Scilla Dependencies [✓] "
cd curpath
printf "Back in Dependencies folder [✓] "
printf "${GREEN}[✓] SCILLA INSTALLED [✓]"


#apt install docker.io
#apt install podman-docker

