#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
echo [+] You wireless interface will now be returned to managed mode!
gnome-terminal --command="bash -c 'iwconfig;$SHELL'"
printf "Whats the name of your device in monitor mode? (Use open terminal window provided to answer)"
read iface
gnome-terminal --command="bash -c 'airmon-ng stop $iface; service NetworkManager restart;$SHELL'"
clear
printf "${GREEN}
-------------------------------------
[✓] WIFI CARD ----> MANAGED MODE [✓] |
-------------------------------------"

sleep 1
