#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
echo '\n[+] Enter target BSSID ---> '
read bssid
echo '\n[+] Enter the channel # ---> '
read channel
echo '\n[+] Choose a name to save your .cap file ---> '
read filename
printf "\n[+] Enter the name of your wireless device ---> " 
read iface
gnome-terminal --command="bash -c 'airodump-ng --bssid $bssid --channel $channel --write $filename $iface; $SHELL'"
printf "${GREEN}
------------------------------------
[✓] 	FINISHED SNIFFING	[✓] |
------------------------------------"

sleep 1
#working
