#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
printf "Interface name (wlan0/eth0 etc...) ---> "
read interface
ifconfig $interface down; sleep 1; ifconfig $interface hw ether 00:11:22:33:44:55; sleep 1; ifconfig $interface up;
echo ''
printf "$GREEN			    [+] New MAC: 00:11:22:33:44:55 [+]"
echo ''
sleep 1


