#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
#
#Using dirbuster to enumerate a website for endpoint detection
read -p "[+] Provide Website/IP: " -r site
dirb $site

