#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
printf 'Enter the URL (with http/https out front) ---> '
read targip
printf 'What wordlist would you like to use?
1) directory-list-2.3-medium.txt (reccomended)
2) directory-list-2.3-small.txt
3) directory-list-lowercase-2.3-medium.txt
4) directory-list-lowercase-2.3-small.txt'
read path
if [ $path == 1 ]
then
#fix it so in the condtional statements it calls the direct path instead of chaning path param
	gnome-terminal --command="bash -c 'feroxbuster --wordlist  wordlists/directory-list-2.3-medium.txt --url $targip;$SHELL'"
	exit
elif [ $path == 2 ]
then

	gnome-terminal --command="bash -c 'feroxbuster --wordlist wordlists/directory-list-2.3-small.txt --url $targip;$SHELL'"
	exit
elif [ $path == 3 ]
then
	gnome-terminal --command="bash -c 'feroxbuster --wordlist wordlists/directory-list-lowercase-2.3-medium.txt --url $targip;$SHELL'"
	exit
elif [ $path == 4 ]
then
	gnome-terminal --command="bash -c 'feroxbuster --wordlist wordlists/directory-list-lowercase-2.3-small.txt --url $targip;$SHELL'"
	exit
else
	printf 'Invalid option selected\n'
	./ferox
	
fi


