#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
#END COLORS
#ready for prod
printf "${YLLW}Enter a url to fuzz (With a / at the end, provide the FULL url, otherwise ffuf wont work. Ex: http://10.10.10.10:8080/): \n"
read url
printf "Would you like to use the defalut wordlist? y/n: "
read list

if [[ $list == 'y' ]] || [[ $list == 'Y' ]]
then
	path="wordlists/directory-list-2.3-medium.txt"
	printf "${GREEN}Starting up ffuf ... \n"
	printf "Get Ready (◕‿◕)\n"
	sleep 1
	ffuf -w $path":FUZZ" -u $url"FUZZ"
elif [[ $list == 'n' ]] || [[ $list == 'N' ]]
then
	printf "Please enter the absolute path to the wordlist of your choice: \n"
	read notDefaultList
	printf "${GREEN}Starting up ffuf ... \n"
	printf "Get Ready (◕‿◕)\n"
	sleep 2
	ffuf -w $notDefaultList":FUZZ" -u $url"FUZZ"
else
	printf "you did not enter a valid option\n"
	printf "resetting this module in 3 seconds ...\n"
	sleep 3
	clear
	./ffufFuzz	
fi

