#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
printf  "${YLLW}[+] Enter the URL you would like to scan ---> "
read url
#nikto -h $url
gnome-terminal --command="bash -c 'nikto -h $url; $SHELL'"
#working
#fixed
clear
printf "${GREEN}
-------------------------------------
[✓] FINISHED SCANNING		 [✓] |
-------------------------------------"

sleep 1
