#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
printf 'Searchsploit ---> '
read query
gnome-terminal --command="bash -c 'searchsploit $query;$SHELL'"
printf "${GREEN}
-------------------------------------
[✓] FINISHED SEARCHING		 [✓] |
-------------------------------------"
