#!/bin/bash
#COLORS
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[1;32m'
YLLW='\033[1;33m'
DG='\033[0;37m'
LR='\033[0;31m'
patch=4.84
#END COLORS
echo ''
echo ''
echo ''
echo ''
echo ''	
printf "${YLLW}
________________________________
Created by:                     |           	
--------------------------------|            	
${RED}	dxrk${YLLW}      		|             	
				|            	
--------------------------------|           	
Contributors:                   |          	
--------------------------------|          	
${GREEN}	asorg ${YLLW}   	        |         	
${GREEN}	krazynez ${YLLW}		|              	
--------------------------------                   "
sleep 2
echo ''
echo ''
echo ''
